CREATE TABLE [dbo].[Registration] (
    [MatrimonyId]           INT           IDENTITY (1, 1) NOT NULL,
    [Profilefor]            VARCHAR (50)  NULL,
    [Name]                  VARCHAR (MAX) NULL,
    [Gender]                VARCHAR (50)  NULL,
    [DOB]                   DATE          NULL,
    [Religion]              VARCHAR (50)  NULL,
    [MotherTongue]          VARCHAR (50)  NULL,
    [Phone]                 VARCHAR (50)  NOT NULL,
    [EmailId]               VARCHAR (MAX) NULL,
    [Password]              VARCHAR (MAX) NULL,
    [Image]                 VARCHAR (MAX) NULL,
    [MaritalStatus]         VARCHAR (MAX) NULL,
    [Height]                VARCHAR (50)  NULL,
    [FamilyStatus]          VARCHAR (50)  NULL,
    [FamilyType]            VARCHAR (50)  NULL,
    [FamilyValues]          VARCHAR (50)  NULL,
    [PhysicallyHandicapped] VARCHAR (50)  NULL,
    [Education]             VARCHAR (50)  NULL,
    [EmployedIn]            VARCHAR (50)  NULL,
    [Occupation]            VARCHAR (50)  NULL,
    [AnnualIncome]          VARCHAR (50)  NULL,
    [LocationCountry]       VARCHAR (50)  NULL,
    [LocationState]         VARCHAR (50)  NULL,
    [LocationCity]          VARCHAR (50)  NULL,
    [BodyType]              VARCHAR (50)  NULL,
    [Weight]                VARCHAR (50)  NULL,
    [Diet]                  VARCHAR (50)  NULL,
    [SmokingHabit]          VARCHAR (50)  NULL,
    [DrinkingHabit]         VARCHAR (50)  NULL,
    [Star]                  VARCHAR (50)  NULL,
    [Rasi]                  VARCHAR (50)  NULL,
    [TimeOfBirth]           VARCHAR (50)  NULL,
    [PlaceofBirthCountry]   VARCHAR (50)  NULL,
    [PlaceofBirthState]     VARCHAR (50)  NULL,
    [PlaceofBirthCity]      VARCHAR (50)  NULL,
    [FatherOccupation]      VARCHAR (MAX) NULL,
    [MotherOccupation]      VARCHAR (50)  NULL,
    [Brothers]              INT           NULL,
    [BrothersMarried]       INT           NULL,
    [Sisters]               INT           NULL,
    [SistersMarried]        INT           NULL,
    [ParentsContact]        VARCHAR (50)  NULL,
    [AncestralOrigin]       VARCHAR (50)  NULL,
    [Page1]                 INT           DEFAULT ((0)) NULL,
    [Page2]                 INT           DEFAULT ((0)) NULL,
    [Page3]                 INT           DEFAULT ((0)) NULL,
    [Otp]                   VARCHAR (50)  NULL,
    [Paid]                  VARCHAR (50)  NULL,
    [LikedProfiles]         INT           NULL,
    [LikedQueue]            VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Phone] ASC)
);

