CREATE TABLE [dbo].[Preference] (
    [Id]                    INT           IDENTITY (1, 1) NOT NULL,
    [Phone]                 VARCHAR (50)  NULL,
    [MaritalStatus]         VARCHAR (MAX) NULL,
    [Height]                VARCHAR (50)  NULL,
    [FamilyStatus]          VARCHAR (50)  NULL,
    [FamilyType]            VARCHAR (50)  NULL,
    [FamilyValues]          VARCHAR (50)  NULL,
    [PhysicallyHandicapped] VARCHAR (50)  NULL,
    [Education]             VARCHAR (50)  NULL,
    [EmployedIn]            VARCHAR (50)  NULL,
    [Occupation]            VARCHAR (50)  NULL,
    [AnnualIncome]          VARCHAR (50)  NULL,
    [LocationCountry]       VARCHAR (50)  NULL,
    [LocationState]         VARCHAR (50)  NULL,
    [LocationCity]          VARCHAR (50)  NULL,
    [BodyType]              VARCHAR (50)  NULL,
    [Weight]                VARCHAR (50)  NULL,
    [Diet]                  VARCHAR (50)  NULL,
    [SmokingHabit]          VARCHAR (50)  NULL,
    [DrinkingHabit]         VARCHAR (50)  NULL,
    [Star]                  VARCHAR (50)  NULL,
    [Rasi]                  VARCHAR (50)  NULL,
    [TimeOfBirth]           VARCHAR (50)  NULL,
    [PlaceofBirthCountry]   VARCHAR (50)  NULL,
    [PlaceofBirthState]     VARCHAR (50)  NULL,
    [PlaceofBirthCity]      VARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([Phone]) REFERENCES [dbo].[Registration] ([Phone])
);

